### ISSUE TITLE
Questions regarding the Section 4 - Experiments

### ISSUE THREAD

**Issue by Magauiya** [jibo27/MemDeblur#2]
Dear authors,

The overall idea of using MB and recurrent model to solve the deblurring task seems very appealing. I would be happy if you find time to clarify some issues in the paper:

- In related works you have mentioned several works, however, they are not presented in Section 4. For example, GSTA [23], which outperforms proposed method (see [VRT](https://arxiv.org/pdf/2201.12288.pdf)). 
- Why the proposed method was not evaluated on other datasets (e.g. commonly known [DVD](https://openaccess.thecvf.com/content_cvpr_2017/papers/Su_Deep_Video_Deblurring_CVPR_2017_paper.pdf))
- It is curious why EDVR works significantly worse than SRN? According to [VRT](https://arxiv.org/pdf/2201.12288.pdf) results (see Table 3), EDVR results are comparable with the proposed one. 

Thank you!

**Comment by jibo27** [comment]
Hi, thanks for your interest and great questions!

- GSTA is an excellent work. However, they have not released source code and do not report computational complexity, making it difficult to compare. 
- We found that the DVD and GOPRO datasets are a bit different, and we have not yet fully explored our approach on the DVD dataset. But if we have time, we will evaluate it on DVD before releasing the code.
- The EDVR result in our paper comes from Table 2 in CDVD-TSP[17]. VRT was released to arxiv after our submission to CVPR, so we didn't refer to it.

**Comment by Magauiya** [comment]
Regarding the second and third points, it would be really interesting to the community to see results on the DVD dataset and will you update/verify EDVR results before the camera-ready submission?  

Thank you for your time!

**Comment by jibo27** [comment]
Hi, thanks for your comments. Unfortunately, the camera-ready submission is due, so we cannot update the camera-ready version. We will evaluate the performance DVD dataset and EDVR results if we have time. We can update the arxiv version then.
